---
id: apifycallerror
title: ApifyCallError
---

<a name="ApifyCallError"></a>

The class represents exceptions thrown by the [`Apify.call()`](../api/apify#module_Apify.call) function.

**Properties**

<table>
<thead>
<tr>
<th>Param</th><th>Type</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>message</code></td><td><code>String</code></td>
</tr>
<tr>
<td colspan="3"><p>Error message</p>
</td></tr><tr>
<td><code>name</code></td><td><code>String</code></td>
</tr>
<tr>
<td colspan="3"><p>Contains <code>&quot;ApifyCallError&quot;</code></p>
</td></tr><tr>
<td><code>run</code></td><td><code><a href="../typedefs/actorrun">ActorRun</a></code></td>
</tr>
<tr>
<td colspan="3"><p>Object representing the failed actor run.</p>
</td></tr></tbody>
</table>
